dp-support #22: ingestion benchmark wrapper script

diff --git a/bin/server-benchmark-ingest-start b/bin/server-benchmark-ingest-start
--- a/bin/server-benchmark-ingest-start
+++ b/bin/server-benchmark-ingest-start
@@ -2,7 +2,7 @@
 
 echo
 echo '================================================================'
-echo 'app-run-ingestion-benchmark'
+echo 'server-ingest-benchmark-start'
 echo '================================================================'
 echo
 
@@ -19,7 +19,7 @@ echo "using DP_HOME: $DP_HOME"
 # check that DP_HOME directory exists
 test -d "$DP_HOME" || { echo "fatal error: configured DP_HOME directory $DP_HOME does not exist"; exit 1; }
 
-APP_NAME='ingestion-benchmark'
+SVC_NAME='dp-benchmark-ingest'
 
 APP_JAR="$DP_HOME/lib/dp-service.jar"
 APP_CONFIG="$DP_HOME/config/dp.yml"
@@ -29,7 +29,7 @@ LOG4J_CONFIG="$DP_HOME/config/log4j2.xml"
 test -z "$JAVA_HOME" && { echo "fatal error: JAVA_HOME variable is not set"; exit 1; }
 
 # check for presence of jar
-test -e "$APP_JAR" || { echo "file APP_JAR $APP_JAR not found"; exit 1; }
+test -e "$APP_JAR" || { echo "fatal error: file APP_JAR $APP_JAR not found"; exit 1; }
 
 # check that app config exists
 test -e "$APP_CONFIG" || { echo "fatal error: app config file: $APP_CONFIG not found"; exit 1; }
@@ -37,9 +37,14 @@ test -e "$APP_CONFIG" || { echo "fatal error: app config file: $APP_CONFIG not f
 # check that log4j config exists
 test -e "$LOG4J_CONFIG" || { echo "fatal error: log4j config file: $LOG4J_CONFIG not found"; exit 1; }
 
-APP_CMD="java -Ddp.config=$APP_CONFIG -Dlog4j.configurationFile=$LOG4J_CONFIG -cp $APP_JAR com.ospreydcs.dp.service.ingest.benchmark.BenchmarkBidiStreamingIngestion"
+# check that bin directory exists
+DP_BIN=$DP_HOME/bin
+test -d "$DP_BIN" || { echo "fatal error: $DP_BIN directory does not exist"; exit 1; }
 
-echo "app_name: $SVC_NAME"
+APP_CMD="java -Ddp.config=$APP_CONFIG -Dlog4j.configurationFile=$LOG4J_CONFIG -cp $APP_JAR com.ospreydcs.dp.service.ingest.benchmark.BenchmarkIngestionGrpcServer"
+
+echo "svc_name: $SVC_NAME"
 echo "app_cmd: $APP_CMD"
 
-eval "$APP_CMD"
+# surround params in single quotes to encapsulate spaces in values etc
+$DP_BIN/util-pm-start \'"$SVC_NAME"\' \'"$APP_CMD"\' || { echo "util-pm-start failed"; exit 1; }
