Created scripts for macOs Query Service.  Updated macOs scripts.

diff --git a/bin/server-start-query-mac-arm64 b/bin/server-start-query-mac-arm64
--- a/bin/server-start-query-mac-arm64
+++ b/bin/server-start-query-mac-arm64
@@ -3,9 +3,10 @@
 # CKA - Modified for macOS bash shell location
 #!/usr/bin/env bash
 
+
 echo
 echo '================================================================'
-echo 'app-run-ingestion-benchmark'
+echo 'server-start-query'
 echo '================================================================'
 echo
 
@@ -22,10 +23,9 @@ echo "using DP_HOME: $DP_HOME"
 # check that DP_HOME directory exists
 test -d "$DP_HOME" || { echo "fatal error: configured DP_HOME directory $DP_HOME does not exist"; exit 1; }
 
-APP_NAME='ingestion-benchmark'
+SVC_NAME='dp-query'
 
-APP_JAR="$DP_HOME/lib/dp-ingest/dp-ingest.jar"
-#APP_CONFIG="$DP_HOME/config/dp-ingest.yml"
+APP_JAR="$DP_HOME/lib/dp-query/dp-query.jar"
 APP_CONFIG="$DP_HOME/config/application.yml"
 LOG4J_CONFIG="$DP_HOME/config/log4j2.xml"
 
@@ -33,7 +33,7 @@ LOG4J_CONFIG="$DP_HOME/config/log4j2.xml"
 test -z "$JAVA_HOME" && { echo "fatal error: JAVA_HOME variable is not set"; exit 1; }
 
 # check for presence of jar
-test -L "$APP_JAR" || { echo "symbolic link $APP_JAR not found, consider creating link to numbered jar version"; exit 1; }
+test -L "$APP_JAR" || { echo "fatal error: symbolic link $APP_JAR not found, consider creating link to numbered version of jar"; exit 1; }
 
 # check that app config exists
 test -e "$APP_CONFIG" || { echo "fatal error: app config file: $APP_CONFIG not found"; exit 1; }
@@ -41,11 +41,16 @@ test -e "$APP_CONFIG" || { echo "fatal error: app config file: $APP_CONFIG not f
 # check that log4j config exists
 test -e "$LOG4J_CONFIG" || { echo "fatal error: log4j config file: $LOG4J_CONFIG not found"; exit 1; }
 
-#APP_CMD="java -Ddp.config=$APP_CONFIG -Dlog4j.configurationFile=$LOG4J_CONFIG -cp $APP_JAR com.ospreydcs.dp.ingest.benchmark.IngestionPerformanceBenchmark"
-APP_CMD="java -Ddp.config=$APP_CONFIG -Dlog4j.configurationFile=$LOG4J_CONFIG -cp $APP_JAR com.ospreydcs.dp.service.ingest.benchmark.IngestionPerformanceBenchmark"
+# check that bin directory exists
+DP_BIN=$DP_HOME/dp-support/current/bin
+test -d "$DP_BIN" || { echo "fatal error: $DP_BIN directory does not exist"; exit 1; }
 
-echo "app_name: $SVC_NAME"
+APP_CMD="java -Ddp.config=$APP_CONFIG -Dlog4j.configurationFile=$LOG4J_CONFIG -jar $APP_JAR"
+
+echo "svc_name: $SVC_NAME"
 echo "app_cmd: $APP_CMD"
 
-eval "$APP_CMD"
+# surround params in single quotes to encapsulate spaces in values etc
+# CKA - modified for macOS arm64: util-pm-start-mac-arm64
+$DP_BIN/util-pm-start-mac-arm64 \'"$SVC_NAME"\' \'"$APP_CMD"\' || { echo "util-pm-start-macOS failed"; exit 1; }
 
