dp-support #7: change scripts to use new .dp.env file to set up environment

diff --git a/bin/server-start-ingest b/bin/server-start-ingest
--- a/bin/server-start-ingest
+++ b/bin/server-start-ingest
@@ -7,28 +7,46 @@ echo 'server-start-ingest'
 echo '================================================================'
 echo
 
-# source ../env/dp-env
+# look for environment config file and source it if it exists
+DP_ENV=( ~/.dp.env )
+test -e "$DP_ENV" || { echo "fatal error: required file $DP_ENV not found"; exit 1; }
+echo "found environment config file: $DP_ENV"
+source $DP_ENV
+
+# check that DP_HOME is defined
+test -z "$DP_HOME" && { echo "fatal error: required DP_HOME variable is not set in $DP_ENV"; exit 1; }
+echo "using DP_HOME: $DP_HOME"
+
+# check that DP_HOME directory exists
+test -d "$DP_HOME" || { echo "fatal error: configured DP_HOME directory $DP_HOME does not exist"; exit 1; }
 
 SVC_NAME='dp-ingest'
 
-# using parens to expand punctuation charactersince double quoting doesn't expand it, alternative is to use:
-# eval LOCKFILE="../var/lock/$SVC_NAME.pid"
-# which could be dangerous if the value is entered by the user
-APP_JAR=( ../../lib/dp-ingest/dp-ingest.jar )
-APP_CONFIG=( ../../config/dp-ingest.yml )
-LOG4J_CONFIG=( ../../config/log4j2.xml )
+APP_JAR="$DP_HOME/lib/dp-ingest/dp-ingest.jar"
+APP_CONFIG="$DP_HOME/config/dp-ingest.yml"
+LOG4J_CONFIG="$DP_HOME/config/log4j2.xml"
+
+# check java home
+test -z "$JAVA_HOME" && { echo "fatal error: JAVA_HOME variable is not set"; exit 1; }
+
+# check for presence of jar
+test -L "$APP_JAR" || { echo "fatal error: symbolic link $APP_JAR not found, consider creating link to numbered version of jar"; exit 1; }
+
+# check that app config exists
+test -e "$APP_CONFIG" || { echo "fatal error: app config file: $APP_CONFIG not found"; exit 1; }
+
+# check that log4j config exists
+test -e "$LOG4J_CONFIG" || { echo "fatal error: log4j config file: $LOG4J_CONFIG not found"; exit 1; }
+
+# check that bin directory exists
+DP_BIN=$DP_HOME/dp-support/current/bin
+test -d "$DP_BIN" || { echo "fatal error: $DP_BIN directory does not exist"; exit 1; }
 
 APP_CMD="java -Ddp.config=$APP_CONFIG -Dlog4j.configurationFile=$LOG4J_CONFIG -jar $APP_JAR"
 
 echo "svc_name: $SVC_NAME"
 echo "app_cmd: $APP_CMD"
 
-# check java home
-test -z "$JAVA_HOME" && { echo "fatal error: JAVA_HOME variable is not set"; exit 1; }
-
-# check for presence of jar
-test -L "$APP_JAR" || { echo "symbolic link $APP_JAR not found, consider creating link to numbered version of jar"; exit 1; }
-
 # surround params in single quotes to encapsulate spaces in values etc
-./util-pm-start \'"$SVC_NAME"\' \'"$APP_CMD"\' || { echo "util-pm-start failed"; exit 1; }
+$DP_BIN/util-pm-start \'"$SVC_NAME"\' \'"$APP_CMD"\' || { echo "util-pm-start failed"; exit 1; }
 
diff --git a/bin/util-pm-start b/bin/util-pm-start
--- a/bin/util-pm-start
+++ b/bin/util-pm-start
@@ -1,7 +1,5 @@
 #!/usr/bin/env bash
 
-# source ~/dp/dp-support/env/dp-env
-
 echo
 echo '================================================================'
 echo 'util-pm-start'
@@ -17,12 +15,13 @@ echo "service command: $APP_CMD"
 
 test -z "$SVC_NAME" && { echo "util-pm-start fatal error: service name parameter not specified"; exit 1; }
 test -z "$APP_CMD" && { echo "util-pm-start fatal error: start command parameter not specified"; exit 1; }
+test -z "$DP_HOME" && { echo "util-pm-start fatal error: DP_HOME not set"; exit 1; }
 
 # using parens to expand the ~ character since double quoting doesn't expand it, alternative is to use:
 # eval LOCKFILE="~/datastore/datastore-deployment/var/lock/$SVC_NAME.pid"
 # which could be dangerous if the value is entered by the user
-LOCKFILE=( ../../var/lock/$SVC_NAME.pid )
-LOGFILE=( ../../var/log/$SVC_NAME.log )
+LOCKFILE="$DP_HOME/var/lock/$SVC_NAME.pid"
+LOGFILE="$DP_HOME/var/log/$SVC_NAME.log"
 
 echo "lockfile: $LOCKFILE"
 echo "logfile: $LOGFILE"
diff --git a/bin/util-pm-stop b/bin/util-pm-stop
--- a/bin/util-pm-stop
+++ b/bin/util-pm-stop
@@ -6,19 +6,15 @@ echo 'util-pm-stop'
 echo '================================================================'
 echo
 
-# source ~/dp/dp-support/env/dp-env
-
 # use eval to eat single quotes containing each param value (so that they can include spaces etc)
 eval SVC_NAME="$1"
 
 echo "stopping service: $SVC_NAME"
 
 test -z "$SVC_NAME" && { echo "util-pm-stop fatal error: service name parameter not specified"; exit 1; }
+test -z "$DP_HOME" && { echo "util-pm-stop fatal error: DP_HOME variable not set"; exit 1; }
 
-# using parens to expand punctuation charactersince double quoting doesn't expand it, alternative is to use:
-# eval LOCKFILE="../var/lock/$SVC_NAME.pid"
-# which could be dangerous if the value is entered by the user
-LOCKFILE=( ../../var/lock/$SVC_NAME.pid )
+LOCKFILE="$DP_HOME/var/lock/$SVC_NAME.pid"
 
 echo "lockfile: $LOCKFILE"
 
